channels:
  - conda-forge
  - defaults
dependencies:
  # - pytorch
  - panel
  - pip:
      - plotly>=5.13
      - pointcloudset==0.9.0
      - ouster-sdk
      - tabulate
      - python-frontmatter
      - dash
      - scikit-learn
      - statsmodels
